In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a.ndim

2

In [4]:
a.shape

(3, 3)

In [5]:
a.size

9

In [6]:
len(a)

3

In [2]:
a=np.array([2,5,7,1,9,3,5,4,0])
a

array([2, 5, 7, 1, 9, 3, 5, 4, 0])

In [3]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 5, 7, 9])

In [4]:
np.argsort(a)

array([8, 3, 0, 5, 7, 1, 6, 2, 4])

In [5]:
a<7

array([ True,  True, False,  True, False,  True,  True,  True,  True])

In [6]:
a[a<7]

array([2, 5, 1, 3, 5, 4, 0])

In [8]:
np.sort?

In [9]:
np.argsort?

In [17]:
a=np.array([[ 0,  1,  2,  3],  
 [ 4,  5,  6,  7],   
 [ 8,  9, 10, 11],   
 [12, 13, 14, 15],   
 [16, 17, 18, 19]])

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
a=a[1:4]
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
a[::,-3::]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [34]:
a=np.array([[ 7, 4, 8, 5, 1],  
 [ 8, 0, 11, 3, 5],  
 [ 9, 6, 3, 5, 0],  
 [ 1, 5, 7, 3, 2],  
 [ 4, 7, 2, 9, 1]])
a

array([[ 7,  4,  8,  5,  1],
       [ 8,  0, 11,  3,  5],
       [ 9,  6,  3,  5,  0],
       [ 1,  5,  7,  3,  2],
       [ 4,  7,  2,  9,  1]])

In [37]:
a=a[a%2==0]
a

array([4, 8, 8, 0, 6, 0, 2, 4, 2])

In [38]:
len(a)

9

In [42]:
a.shape

(9,)

In [43]:
np.sqrt(9)

3.0

In [44]:
np.argmin(a)

3

In [45]:
np.argmin?

In [46]:
np.argmax?

In [47]:
a

array([4, 8, 8, 0, 6, 0, 2, 4, 2])

In [48]:
a=np.array([1,2,3,4])
b=np.array([5,6,2,3])

In [49]:
a>b

array([False, False,  True,  True])

In [50]:
np.any(a>b)

True

In [51]:
np.all(a>b)

False

In [52]:
np.any?

In [53]:
np.all?

In [55]:
c=np.array([[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]])

In [56]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [57]:
c[1, :, :]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [58]:
a=np.array([-3,4,10,60,-100,20,30,-4])
a

array([  -3,    4,   10,   60, -100,   20,   30,   -4])

In [60]:
np.where(a>0,+1,-1)

array([-1,  1,  1,  1, -1,  1,  1, -1])

In [62]:
np.where(a>0,+1,a)

array([  -3,    1,    1,    1, -100,    1,    1,   -4])

In [63]:
np.where(a>0)

(array([1, 2, 3, 5, 6]),)

In [64]:
ls

DV.ipynb
Descriptive Stat.ipynb
Gaussian Distribution.ipynb
NPS.ipynb
Netflix project II.ipynb
Netflix project.ipynb
Numpy Airbnb NPS final .ipynb
Numpy_Interview_Prep.ipynb
Pandas Revision.ipynb
Pandas final cut.ipynb
Pfizer_1.csv
Prob and Stat/
Python Lib Rivision.ipynb
Python revision.ipynb
SQL/
These Are the 25 Smartest Dog Breeds, According to Science.jpeg
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
clouds-2627945.jpg
directors.csv
figure.png
final_vg.csv
fit.txt
gapminder.csv
jupyterthemes.ipynb
mckinsey.csv
movies.csv
sales (1).csv
sales.csv
storytelling-with-data-cole-nussbaumer-knaflic.pdf
survey.txt


In [66]:
data=np.loadtxt("fit.txt",dtype='str')
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [67]:
data.shape

(96, 6)

In [68]:
data[:,0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [69]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [70]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [85]:
date,step_count,mood,calories_burn,hr_of_sleep,active=data.T

In [72]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [102]:
step_count=np.array(step_count,dtype='int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [78]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [79]:
np.unique(active,return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

In [80]:
np.mean(step_count)

2935.9375

In [81]:
np.max(step_count)

7422

In [82]:
np.argmax(step_count)

69

In [83]:
date[np.argmax(step_count)]

'14-12-2017'

In [86]:
mood=='Sad'

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False, False])

In [103]:
step_count[mood=='Sad']

array([6041,   25, 5461, 4545, 4340, 1230,   61, 1258, 3148, 4687, 3519,
       1580, 2822,  181, 6676, 3721, 1648,  799, 1696,  221, 4061,  651,
        753,  518,  177,   36,  299,  702,  133])

In [104]:
np.mean(step_count[mood=='Sad'])

2103.0689655172414

In [106]:
np.mean(step_count[mood=='Happy'])

3392.725

In [107]:
np.mean(step_count[mood=='Neutral'])

3153.777777777778

In [108]:
step_count>4000

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [109]:
mood[step_count>4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [112]:
np.unique(mood[step_count>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [114]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [117]:
np.identity(3)*9

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])