In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [3]:
b=[i**2 for i in a]
b

[1, 4, 9, 16, 25]

In [4]:
for i in a:
    print(i**2)

1
4
9
16
25


In [5]:
c=[]
for i in a:
    c.append(i**2)
c

[1, 4, 9, 16, 25]

In [6]:
d=np.array([1,2,3,4,5])
d

array([1, 2, 3, 4, 5])

In [7]:
d**2

array([ 1,  4,  9, 16, 25])

In [9]:
l=range(0,100000)
l

range(0, 100000)

In [10]:
[i**2 for i in l]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 2

In [11]:
t=np.array(l)
t

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [12]:
%timeit [i**2 for i in l]

44.8 ms ± 2.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit t**2

104 µs ± 6.79 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [15]:
a.shape[0]

6

In [16]:
a.size

6

In [17]:
a.ndim

1

In [18]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.dtype

dtype('int64')

In [21]:
a

array([1, 2, 3, 4, 5, 6])

In [22]:
list(map(lambda x:x+1, a))

[2, 3, 4, 5, 6, 7]

# Day 2

In [23]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a[0]

1

In [25]:
a[5]

6

In [26]:
a[3]

4

In [27]:
a[-1]

8

In [28]:
a[7]

8

In [29]:
a[-3]

6

In [30]:
a[-5]

4

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
 a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a[[0,3,4]]

array([1, 4, 5])

In [38]:
a[[-6,-4,-3]]

array([3, 5, 6])

In [39]:
a[[0,-8]]

array([1, 1])

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a[1:4]

array([2, 3, 4])

In [42]:
a[-1:-8:-1]

array([8, 7, 6, 5, 4, 3, 2])

In [43]:
a[-1:-8:1]

array([], dtype=int64)

In [44]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
a<15

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [47]:
a<5

array([ True,  True,  True,  True, False, False, False, False])

In [48]:
a[a<5]

array([1, 2, 3, 4])

In [49]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True])

In [50]:
a[a%2==0]

array([2, 4, 6, 8])

In [52]:
(a%2==0)|(a%5==0)

array([False,  True, False,  True,  True,  True, False,  True])

In [53]:
a[(a%2==0)|(a%5==0)]

array([2, 4, 5, 6, 8])

In [54]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([6,7,8,9,10,11])

In [55]:
a+10

array([11, 12, 13, 14, 15])

In [56]:
a<10

array([ True,  True,  True,  True,  True])

In [57]:
a+b

array([ 7,  9, 11, 13, 15])

In [58]:
a+c

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [59]:
b+c

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [60]:
a<c

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [61]:
np.all(a<b)

True

In [62]:
np.all(a>b)

False

In [63]:
np.any(a<b)

True

In [64]:
np.mean(a)

3.0

In [65]:
a.mean()

3.0

In [66]:
np.min(a)

1

In [67]:
a.min()

1

In [68]:
ls

06_Probability_Distributions_1/
07_Probability_Distributions_2/
Data Via conti..ipynb
Data Viz with seaborn.ipynb
Data_Vizzzzzz.ipynb
MatplotLib conti. + Seaborn.ipynb
Matplotlib.ipynb
Matplotlib_Revision.ipynb
Netflix project.ipynb
Numpy Airbnb NPS final .ipynb
Numpy Final-Cut.ipynb
Numpy Final.ipynb
Pandas Final-Cut.ipynb
Pandas_4.ipynb
Pandas_5.ipynb
Pandas_Rev_conti.ipynb
Pandas_Revision.ipynb
Pfizer_1.csv
Probability Day 1.ipynb
Probability Day 2.ipynb
Probability basic defination.ipynb
Probablity 1 retake.ipynb
SQL/
These Are the 25 Smartest Dog Breeds, According to Science.jpeg
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
clouds-2627945.jpg
directors.csv
figure.png
fit.txt
gapminder.csv
jupyterthemes.ipynb
mckinsey.csv
movies.csv
numpy_pandas_revision.ipynb
prob_01_basic_definitions/
survey.txt


In [69]:
data=np.loadtxt("survey.txt")
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [70]:
len(data)

1167

In [74]:
data.shape

(1167,)

In [75]:
data.shape[0]

1167

In [76]:
data.size

1167

In [77]:
total=data.shape[0]
total

1167

In [81]:
de=data[data<7].shape[0]
de

332

In [82]:
pro=data[data>8].shape[0]
pro

609

In [83]:
per_pro=pro/total
per_pro

0.5218508997429306

In [84]:
per_de=de/total
per_de

0.28449014567266495

In [85]:
nps=(per_pro-per_de)*100
nps

23.73607540702657

In [86]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
a.ndim

2

In [88]:
a.shape

(2, 3)

In [90]:
a.size

6

In [91]:
len(a)

2

In [92]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [93]:
a.shape

(12,)

In [94]:
a.ndim

1

In [95]:
a.size

12

In [96]:
b=a.reshape((3,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
b.shape

(3, 4)

In [98]:
b.size

12

In [99]:
b.ndim

2