In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a.ndim

2

In [4]:
a.shape

(3, 3)

In [5]:
a.size

9

In [6]:
len(a)

3

In [2]:
a=np.array([2,5,7,1,9,3,5,4,0])
a

array([2, 5, 7, 1, 9, 3, 5, 4, 0])

In [3]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 5, 7, 9])

In [4]:
np.argsort(a)

array([8, 3, 0, 5, 7, 1, 6, 2, 4])

In [5]:
a<7

array([ True,  True, False,  True, False,  True,  True,  True,  True])

In [6]:
a[a<7]

array([2, 5, 1, 3, 5, 4, 0])