In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [3]:
b=[i**2 for i in a]
b

[1, 4, 9, 16, 25]

In [4]:
for i in a:
    print(i**2)

1
4
9
16
25


In [5]:
c=[]
for i in a:
    c.append(i**2)
c

[1, 4, 9, 16, 25]

In [6]:
d=np.array([1,2,3,4,5])
d

array([1, 2, 3, 4, 5])

In [7]:
d**2

array([ 1,  4,  9, 16, 25])

In [9]:
l=range(0,100000)
l

range(0, 100000)

In [10]:
[i**2 for i in l]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 2

In [11]:
t=np.array(l)
t

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [12]:
%timeit [i**2 for i in l]

44.8 ms ± 2.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit t**2

104 µs ± 6.79 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [15]:
a.shape[0]

6

In [16]:
a.size

6

In [17]:
a.ndim

1

In [18]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.dtype

dtype('int64')

In [21]:
a

array([1, 2, 3, 4, 5, 6])

In [22]:
list(map(lambda x:x+1, a))

[2, 3, 4, 5, 6, 7]

# Day 2

In [23]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a[0]

1

In [25]:
a[5]

6

In [26]:
a[3]

4

In [27]:
a[-1]

8

In [28]:
a[7]

8

In [29]:
a[-3]

6

In [30]:
a[-5]

4

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
 a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a[[0,3,4]]

array([1, 4, 5])

In [38]:
a[[-6,-4,-3]]

array([3, 5, 6])

In [39]:
a[[0,-8]]

array([1, 1])

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a[1:4]

array([2, 3, 4])

In [42]:
a[-1:-8:-1]

array([8, 7, 6, 5, 4, 3, 2])

In [43]:
a[-1:-8:1]

array([], dtype=int64)

In [44]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
a<15

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [47]:
a<5

array([ True,  True,  True,  True, False, False, False, False])

In [48]:
a[a<5]

array([1, 2, 3, 4])

In [49]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True])

In [50]:
a[a%2==0]

array([2, 4, 6, 8])

In [52]:
(a%2==0)|(a%5==0)

array([False,  True, False,  True,  True,  True, False,  True])

In [53]:
a[(a%2==0)|(a%5==0)]

array([2, 4, 5, 6, 8])

In [54]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([6,7,8,9,10,11])

In [55]:
a+10

array([11, 12, 13, 14, 15])

In [56]:
a<10

array([ True,  True,  True,  True,  True])

In [57]:
a+b

array([ 7,  9, 11, 13, 15])

In [58]:
a+c

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [59]:
b+c

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [60]:
a<c

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [61]:
np.all(a<b)

True

In [62]:
np.all(a>b)

False

In [63]:
np.any(a<b)

True

In [64]:
np.mean(a)

3.0

In [65]:
a.mean()

3.0

In [66]:
np.min(a)

1

In [67]:
a.min()

1

In [68]:
ls

06_Probability_Distributions_1/
07_Probability_Distributions_2/
Data Via conti..ipynb
Data Viz with seaborn.ipynb
Data_Vizzzzzz.ipynb
MatplotLib conti. + Seaborn.ipynb
Matplotlib.ipynb
Matplotlib_Revision.ipynb
Netflix project.ipynb
Numpy Airbnb NPS final .ipynb
Numpy Final-Cut.ipynb
Numpy Final.ipynb
Pandas Final-Cut.ipynb
Pandas_4.ipynb
Pandas_5.ipynb
Pandas_Rev_conti.ipynb
Pandas_Revision.ipynb
Pfizer_1.csv
Probability Day 1.ipynb
Probability Day 2.ipynb
Probability basic defination.ipynb
Probablity 1 retake.ipynb
SQL/
These Are the 25 Smartest Dog Breeds, According to Science.jpeg
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
clouds-2627945.jpg
directors.csv
figure.png
fit.txt
gapminder.csv
jupyterthemes.ipynb
mckinsey.csv
movies.csv
numpy_pandas_revision.ipynb
prob_01_basic_definitions/
survey.txt


In [69]:
data=np.loadtxt("survey.txt")
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [70]:
len(data)

1167

In [74]:
data.shape

(1167,)

In [75]:
data.shape[0]

1167

In [76]:
data.size

1167

In [77]:
total=data.shape[0]
total

1167

In [81]:
de=data[data<7].shape[0]
de

332

In [82]:
pro=data[data>8].shape[0]
pro

609

In [83]:
per_pro=pro/total
per_pro

0.5218508997429306

In [84]:
per_de=de/total
per_de

0.28449014567266495

In [85]:
nps=(per_pro-per_de)*100
nps

23.73607540702657

In [86]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
a.ndim

2

In [88]:
a.shape

(2, 3)

In [90]:
a.size

6

In [91]:
len(a)

2

In [92]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [93]:
a.shape

(12,)

In [94]:
a.ndim

1

In [95]:
a.size

12

In [96]:
b=a.reshape((3,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
b.shape

(3, 4)

In [98]:
b.size

12

In [99]:
b.ndim

2

# Day 3

In [100]:
a-np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [101]:
b=a.reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [103]:
a.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
b[1][1]

6

In [108]:
b[1,1]

6

In [109]:
b[2,2]

11

In [110]:
b[-1,-2]

11

In [111]:
b[2,-2]

11

In [114]:
b[[1,2],[1,2]]

array([ 6, 11])

In [115]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
b[[1,2,2],[1,2,3]]

array([ 6, 11, 12])

In [117]:
b[[0,2,2],[2,3,0]]

array([ 3, 12,  9])

In [118]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
b[::,::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
b[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [121]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
b<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [123]:
b[b<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
b.mean()

6.5

In [125]:
np.mean(b)

6.5

In [126]:
np.sum(b)

78

In [127]:
b.sum()

78

In [128]:
b.min()

1

In [129]:
np.min(b)

1

In [130]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [131]:
np.sort(b)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [132]:
b=b.T
b

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [133]:
np.sort(b)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [134]:
np.sort(b,axis=1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [135]:
np.sort(b,axis=0)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# Day 4

In [136]:
ls

06_Probability_Distributions_1/
07_Probability_Distributions_2/
Data Via conti..ipynb
Data Viz with seaborn.ipynb
Data_Vizzzzzz.ipynb
MatplotLib conti. + Seaborn.ipynb
Matplotlib.ipynb
Matplotlib_Revision.ipynb
Netflix project.ipynb
Numpy Airbnb NPS final .ipynb
Numpy Final-Cut.ipynb
Numpy Final.ipynb
Pandas Final-Cut.ipynb
Pandas_4.ipynb
Pandas_5.ipynb
Pandas_Rev_conti.ipynb
Pandas_Revision.ipynb
Pfizer_1.csv
Probability Day 1.ipynb
Probability Day 2.ipynb
Probability basic defination.ipynb
Probablity 1 retake.ipynb
SQL/
These Are the 25 Smartest Dog Breeds, According to Science.jpeg
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
clouds-2627945.jpg
directors.csv
figure.png
fit.txt
gapminder.csv
jupyterthemes.ipynb
mckinsey.csv
movies.csv
numpy_pandas_revision.ipynb
prob_01_basic_definitions/
survey.txt


In [137]:
data=np.loadtxt("survey.txt")
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [138]:
np.unique(data)

array([ 1.,  4.,  5.,  7.,  8.,  9., 10.])

In [140]:
np.unique(data,return_counts=True)

(array([ 1.,  4.,  5.,  7.,  8.,  9., 10.]),
 array([117, 112, 103, 123, 103, 394, 215]))

In [141]:
a=np.array([2,1,6,4,7,3,8,9,11])
a

array([ 2,  1,  6,  4,  7,  3,  8,  9, 11])

In [142]:
a<6

array([ True,  True, False,  True, False,  True, False, False, False])

In [143]:
np.where(a<6)

(array([0, 1, 3, 5]),)

In [144]:
np.where(a<6,-1,+1)

array([-1, -1,  1, -1,  1, -1,  1,  1,  1])

In [145]:
np.where(a<6,-1,a)

array([-1, -1,  6, -1,  7, -1,  8,  9, 11])

In [146]:
ls

06_Probability_Distributions_1/
07_Probability_Distributions_2/
Data Via conti..ipynb
Data Viz with seaborn.ipynb
Data_Vizzzzzz.ipynb
MatplotLib conti. + Seaborn.ipynb
Matplotlib.ipynb
Matplotlib_Revision.ipynb
Netflix project.ipynb
Numpy Airbnb NPS final .ipynb
Numpy Final-Cut.ipynb
Numpy Final.ipynb
Pandas Final-Cut.ipynb
Pandas_4.ipynb
Pandas_5.ipynb
Pandas_Rev_conti.ipynb
Pandas_Revision.ipynb
Pfizer_1.csv
Probability Day 1.ipynb
Probability Day 2.ipynb
Probability basic defination.ipynb
Probablity 1 retake.ipynb
SQL/
These Are the 25 Smartest Dog Breeds, According to Science.jpeg
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
clouds-2627945.jpg
directors.csv
figure.png
fit.txt
gapminder.csv
jupyterthemes.ipynb
mckinsey.csv
movies.csv
numpy_pandas_revision.ipynb
prob_01_basic_definitions/
survey.txt


In [150]:
data=np.loadtxt("fit.txt",dtype="str")
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [151]:
date=data[::,0]
step_count=data[::,1]
mod=data[::,2]
calories_burn=data[::,3]
hr_of_sleep=data[::,4]
active=data[::,5]

In [152]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [153]:
step_count=np.array(step_count,dtype="int")
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [154]:
calories_burn=np.array(calories_burn,dtype="int")
calories_burn

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [155]:
hr_of_sleep=np.array(hr_of_sleep,dtype="int")
hr_of_sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [156]:
np.mean(step_count)

2935.9375

In [157]:
np.unique(mod)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [158]:
np.unique(mod,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [159]:
np.unique(active,return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

In [160]:
np.argmax(step_count)

69

In [161]:
date[69]

'14-12-2017'

In [162]:
date[np.argmax(step_count)]

'14-12-2017'

In [164]:
mod=="Sad"

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False, False])

In [165]:
step_count[mod=="Sad"]

array([6041,   25, 5461, 4545, 4340, 1230,   61, 1258, 3148, 4687, 3519,
       1580, 2822,  181, 6676, 3721, 1648,  799, 1696,  221, 4061,  651,
        753,  518,  177,   36,  299,  702,  133])

In [166]:
np.mean(step_count[mod=="Sad"])

2103.0689655172414

In [167]:
np.mean(step_count[mod=="Neutral"])

3153.777777777778

In [168]:
np.mean(step_count[mod=="Happy"])

3392.725

In [169]:
step_count>4000

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [170]:
mod[step_count>4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [171]:
np.unique(mod[step_count>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [172]:
np.unique(mod[step_count>2000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([27, 19, 11]))

In [174]:
np.unique(mod[hr_of_sleep<4],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([1, 5, 6]))

In [175]:
np.unique(mod[hr_of_sleep>4],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([33, 18, 19]))

In [176]:
np.unique(mod[active=="Inactive"],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([16, 13, 25]))

In [177]:
np.unique(mod[active=="Active"],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([24, 14,  4]))

In [181]:
np.mean(hr_of_sleep[mod=="Happy"])

5.725

In [182]:
np.mean(hr_of_sleep[mod=="Sad"])

5.0344827586206895

In [184]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [185]:
import math
math.log

<function math.log>

In [186]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [187]:
y=np.vectorize(math.log)
y(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [188]:
def fun_fun(x):
    if x%2==0:
        return x**2
    else:
        return x**3

In [189]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [190]:
y=np.vectorize(fun_fun)
y

In [191]:
y(a)

array([  1,   4,  27,  16, 125,  36, 343,  64, 729, 100])