<a href="https://colab.research.google.com/github/jeeet0700/Numpy/blob/main/Numpy_inter_prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a<3

array([ True,  True, False, False, False, False])

In [4]:
a[a<3]

array([1, 2])