In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5,6]
b=[i**2 for i in a]
b

[1, 4, 9, 16, 25, 36]

In [3]:
a=np.array([1,2,3,4,5,6])
a**2

array([ 1,  4,  9, 16, 25, 36])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
a=range(100000)

In [7]:
%timeit [i**2 for i in a]

42.3 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
b=np.arange(100000)

In [10]:
%timeit b**2

96.8 µs ± 4.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
type(np.array([1,2,3]))

numpy.ndarray

In [13]:
(np.array([1,2,3.3])).dtype

dtype('float64')

In [14]:
a

range(0, 100000)

In [15]:
a=np.array([1,2,3,4,5,6])
a.ndim

1

In [16]:
a.shape

(6,)

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a.ndim

2

In [25]:
a.shape

(3, 3)

In [26]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [28]:
a.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])