## Numpy D1

In [4]:
import numpy as np

In [2]:
a=[1,2,3,4,5,6]
b=[i**2 for i in a]
b

[1, 4, 9, 16, 25, 36]

In [3]:
a=np.array([1,2,3,4,5,6])
a**2

array([ 1,  4,  9, 16, 25, 36])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
a=range(100000)

In [7]:
%timeit [i**2 for i in a]

42.3 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
b=np.arange(100000)

In [10]:
%timeit b**2

96.8 µs ± 4.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
type(np.array([1,2,3]))

numpy.ndarray

In [13]:
(np.array([1,2,3.3])).dtype

dtype('float64')

In [14]:
a

range(0, 100000)

In [15]:
a=np.array([1,2,3,4,5,6])
a.ndim

1

In [16]:
a.shape

(6,)

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a.ndim

2

In [25]:
a.shape

(3, 3)

In [26]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [28]:
a.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [29]:
a.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [30]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
a.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [32]:
b=a.reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [34]:
a=np.arange(1,13).reshape(3,4)

In [35]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
a[0:5]

array([1, 2, 3, 4, 5])

In [38]:
a[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [40]:
a[-4:]

array([ 9, 10, 11, 12])

In [41]:
a[::2]

array([ 1,  3,  5,  7,  9, 11])

In [42]:
a[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [43]:
a[::-2]

array([12, 10,  8,  6,  4,  2])

In [44]:
a[-10:-2:-1]

array([], dtype=int64)

In [46]:
a[-10:-2:1]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a=np.arange(1,13).reshape(3,4)

In [48]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[:1]

array([[1, 2, 3, 4]])

In [50]:
a[1]

array([5, 6, 7, 8])

In [54]:
a[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a[1:3,1:2]

array([[ 6],
       [10]])

In [56]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
a=a.reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
a[::2,::2]

array([[1, 3],
       [7, 9]])

In [60]:
a[:,2]

array([ 3,  6,  9, 12])

In [61]:
a[:,1]

array([ 2,  5,  8, 11])

In [62]:
a[:,0]

array([ 1,  4,  7, 10])

In [63]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [64]:
list(map(lambda x:x+1, A))

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [65]:
[x+1 for x in A]

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [66]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
a[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [85]:
np.linspace(5,7,10)

array([5.        , 5.22222222, 5.44444444, 5.66666667, 5.88888889,
       6.11111111, 6.33333333, 6.55555556, 6.77777778, 7.        ])

In [86]:
np.arange(5,10,3)

array([5, 8])

In [82]:
a[:,1]

array([ 2,  6, 10])

In [83]:
a[[0,0,1,2],[0,2,3,1]]

array([ 1,  3,  8, 10])

In [87]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
a>40

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [93]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [94]:
a=np.arange(1,13)

In [95]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
a[1]

2

In [97]:
a[-1]

12

In [98]:
a[:5]

array([1, 2, 3, 4, 5])

In [99]:
a[-5:-1]

array([ 8,  9, 10, 11])

In [101]:
a[-5:-1:-1]

array([], dtype=int64)

In [103]:
b=np.array([1,2,3,4,5,6])
b[4:]=10
b

array([ 1,  2,  3,  4, 10, 10])

In [109]:
a=np.array([1,2,3,4,5])
b=np.array([8,7,6])
a[2:]=b[::-1]
a

array([1, 2, 6, 7, 8])

In [110]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
a<6 #mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False])

In [112]:
a[a<6]

array([1, 2, 3, 4, 5])

In [113]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [114]:
(a%2==0) | (a%5==0)

array([False,  True, False,  True,  True,  True, False,  True, False,
        True, False,  True])

In [115]:
a[(a%2==0) | (a%5==0)]

array([ 2,  4,  5,  6,  8, 10, 12])

In [116]:
np.array([1,2,3])+np.array([3,2,1])

array([4, 4, 4])

In [117]:
np.array([1,2,3])+np.array([3,2,1,1])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [118]:
np.sum(np.array([1,2,3,4,5,6]))

21

In [119]:
np.mean(np.array([1,2,3,4,5]))

3.0

In [120]:
np.min(np.array([2,6,3,9,6,78,1]))

1

In [121]:
np.max(np.array([3,2,7,4,9,8,9,5,4]))

9

In [122]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

/bin/bash: gdown: command not found


In [123]:
pip install gdown

Note: you may need to restart the kernel to use updated packages.


In [1]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /Users/jitendranathmahato/Downloads/Scaler/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 1.81MB/s]


In [2]:
ls

06_Probability_Distributions_1/
07_Probability_Distributions_2/
Data Via conti..ipynb
Data Viz with seaborn.ipynb
Data_Vizzzzzz.ipynb
MatplotLib conti. + Seaborn.ipynb
Matplotlib.ipynb
Matplotlib_Revision.ipynb
Netflix project.ipynb
Numpy Final-Cut.ipynb
Numpy Final.ipynb
Pandas_4.ipynb
Pandas_5.ipynb
Pandas_Rev_conti.ipynb
Pandas_Revision.ipynb
Pfizer_1.csv
Probability Day 1.ipynb
Probability Day 2.ipynb
Probability basic defination.ipynb
Probablity 1 retake.ipynb
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
directors.csv
drive.google.com/
figure.png
gapminder.csv
jupyterthemes.ipynb
movies.csv
numpy_pandas_revision.ipynb
prob_01_basic_definitions/
survey.txt


In [5]:
survey=np.loadtxt("survey.txt",dtype="int")

In [6]:
survey

array([ 7, 10,  5, ...,  5,  9, 10])

In [7]:
survey.ndim

1

In [8]:
survey.shape

(1167,)

In [9]:
np.min(survey)

1

In [10]:
np.max(survey)

10

In [11]:
#NPS = %Promoter - %Detractor

In [14]:
survey[survey<=6].shape

(332,)

In [18]:
n_detractors=survey[survey<=6].shape[0]

In [19]:
total=survey.shape[0]
total

1167

In [21]:
per_detractors=(n_detractors/total)*100
per_detractors

28.449014567266495

In [22]:
promoters=survey[survey>=9].shape[0]
per_promoters = (promoters/total)*100
per_promoters

52.185089974293064

In [23]:
nps=per_promoters-per_detractors
nps

23.73607540702657

## Day 2

In [25]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
a.ndim

2

In [27]:
a.shape

(2, 4)

In [28]:
a.size

8

In [29]:
len(a)

2

In [30]:
a=np.arange(3).reshape(1,3)
a #row vector

array([[0, 1, 2]])

In [31]:
a.T #columns vector

array([[0],
       [1],
       [2]])

In [32]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a[1]

array([4, 5, 6])

In [34]:
a[1][2]

6

In [35]:
a[1,2]

6

In [36]:
a[[0,1,2],[0,1,2]]

array([1, 5, 9])

In [37]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
a[:,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [41]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [42]:
a[:,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [43]:
a[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [44]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [46]:
a[a<6]

array([0, 1, 2, 3, 4, 5])

In [47]:
a.sum()

66

In [48]:
np.sum(a)

66

In [50]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [52]:
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [53]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
a<b

array([ True,  True, False, False])

In [54]:
np.all(a<b)

False

In [58]:
(a<b).all()

False

In [55]:
np.any(a<b)

True

In [59]:
(a<b).any()

True

In [62]:
np.where(a>3,+4,-4)

array([-4, -4, -4,  4])

In [61]:
a

array([1, 2, 3, 4])

In [64]:
a.sort()
a

array([1, 2, 3, 4])

In [65]:
a=np.array([3,5,7,9,2,3,1])
a

array([3, 5, 7, 9, 2, 3, 1])

In [67]:
a.sort()
a

array([1, 2, 3, 3, 5, 7, 9])

In [68]:
a

array([1, 2, 3, 3, 5, 7, 9])

In [69]:
a=np.array([3,5,7,9,2,3,1])
a

array([3, 5, 7, 9, 2, 3, 1])

In [70]:
np.sort(a)

array([1, 2, 3, 3, 5, 7, 9])

In [71]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
a=a.T
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [75]:
a[:,::-1]

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [79]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [80]:
sorted_age_index = np.argsort(age)
sorted_age_index

array([3, 7, 4, 2, 6, 5, 0, 8, 1, 9])

In [81]:
result =  birds[sorted_age_index]
result

TypeError: only integer scalar arrays can be converted to a scalar index

In [88]:
a=np.arange(0,20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [89]:
a=a[1:4,1:4]
a

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [90]:
a[::-1]

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

## Day 3

In [91]:
ls

06_Probability_Distributions_1/
07_Probability_Distributions_2/
Data Via conti..ipynb
Data Viz with seaborn.ipynb
Data_Vizzzzzz.ipynb
MatplotLib conti. + Seaborn.ipynb
Matplotlib.ipynb
Matplotlib_Revision.ipynb
Netflix project.ipynb
Numpy Final-Cut.ipynb
Numpy Final.ipynb
Pandas_4.ipynb
Pandas_5.ipynb
Pandas_Rev_conti.ipynb
Pandas_Revision.ipynb
Pfizer_1.csv
Probability Day 1.ipynb
Probability Day 2.ipynb
Probability basic defination.ipynb
Probablity 1 retake.ipynb
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
directors.csv
drive.google.com/
figure.png
gapminder.csv
jupyterthemes.ipynb
movies.csv
numpy_pandas_revision.ipynb
prob_01_basic_definitions/
survey.txt


In [92]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /Users/jitendranathmahato/Downloads/Scaler/fit.txt
100%|███████████████████████████████████████| 3.43k/3.43k [00:00<00:00, 618kB/s]


In [93]:
ls

06_Probability_Distributions_1/
07_Probability_Distributions_2/
Data Via conti..ipynb
Data Viz with seaborn.ipynb
Data_Vizzzzzz.ipynb
MatplotLib conti. + Seaborn.ipynb
Matplotlib.ipynb
Matplotlib_Revision.ipynb
Netflix project.ipynb
Numpy Final-Cut.ipynb
Numpy Final.ipynb
Pandas_4.ipynb
Pandas_5.ipynb
Pandas_Rev_conti.ipynb
Pandas_Revision.ipynb
Pfizer_1.csv
Probability Day 1.ipynb
Probability Day 2.ipynb
Probability basic defination.ipynb
Probablity 1 retake.ipynb
Think Stats, 2nd Edition_ Exploratory Data Analysis ( PDFDrive ).pdf
Untitled.ipynb
directors.csv
drive.google.com/
figure.png
fit.txt
gapminder.csv
jupyterthemes.ipynb
movies.csv
numpy_pandas_revision.ipynb
prob_01_basic_definitions/
survey.txt


In [96]:
fit=np.loadtxt("fit.txt",dtype="str")
fit

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [97]:
fit[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [99]:
fit_T=fit.T
fit_T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [100]:
fit_T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [101]:
fit_bit.shape

(96, 6)

In [102]:
fit_bit.size

576